const key = 'goods-purchase-log-v1';
const initial = { goods:[{id:'demo-tee',name:'Tシャツ',event:'',quantity:1,stock:2,price:4000,memo:'',photo:''}], random:[], plans:[], venueNames:[], venue:'all' };
let state = load(); let page = 'home'; let editing = null; let pendingDelete = null;
const app = document.querySelector('#app');

function load(){ try { return {...initial,...JSON.parse(localStorage.getItem(key))}; } catch { return structuredClone(initial); } }
function save(){ localStorage.setItem(key, JSON.stringify(state)); render(); }
function yen(v){ return `¥${Number(v||0).toLocaleString('ja-JP')}`; }
function id(){ return crypto.randomUUID?.() || `${Date.now()}-${Math.random()}`; }
function esc(s=''){ const e=document.createElement('span'); e.textContent=s; return e.innerHTML; }
function venues(){ return [...new Set([...(state.venueNames||[]),...state.goods,...state.plans,...state.random].map(x=>typeof x==='string'?x:x.event).filter(Boolean))]; }
function photo(src){ return src ? `<img class="thumb" src="${src}" alt="">` : '<div class="thumb">✦</div>'; }
function filterVenue(items){ return state.venue==='all' ? items : items.filter(x=>x.event===state.venue); }
function empty(text){ return `<div class="empty"><span class="emoji">☁</span>${text}</div>`; }
function row(item,type){ const amount=type==='goods' ? Number(item.quantity||0)*Number(item.price||0) : type==='plans'&&Number(item.price||0)>0 ? Number(item.price)*Number(item.quantity||1) : ''; const sub=type==='goods' ? `${item.event||'現場未設定'} ・ 購入 ${item.quantity||0}個 / 在庫 ${item.stock||0}個` : type==='random' ? `${item.event||'現場未設定'} ・ 出た数 ${item.quantity||0}個` : `${item.event||'現場未設定'} ・ 予定 ${item.quantity||1}個${item.category?` ・ ${item.category}`:''}`; return `<div class="row">${photo(item.photo)}<div class="row-main"><p class="row-title">${esc(item.name)}</p><p class="row-sub">${esc(sub)}${item.memo?`<br>${esc(item.memo)}`:''}</p></div>${amount?`<span class="row-price">${yen(amount)}</span>`:''}<div class="row-actions">${type==='random'?`<button class="mini plus" data-id="${item.id}" title="1個増やす">＋</button>`:''}<button class="mini edit" data-type="${type}" data-id="${item.id}" title="編集">✎</button><button class="mini delete" data-type="${type}" data-id="${item.id}" title="削除">⌫</button></div></div>`; }
function venueChips(){ return `<div class="filters"><button class="chip ${state.venue==='all'?'active':''}" data-venue="all">すべて</button>${venues().map(v=>`<button class="chip ${state.venue===v?'active':''}" data-venue="${esc(v)}">${esc(v)}</button>`).join('')}</div>`; }
function home(){ const goods=filterVenue(state.goods); const spent=goods.reduce((a,x)=>a+Number(x.price||0)*Number(x.quantity||0),0); const stock=goods.reduce((a,x)=>a+Number(x.stock||0),0); const venueNames=[...new Set([...venues(),...state.goods.map(x=>x.event||'__unset__')])]; const venueTotals=venueNames.map(v=>({key:v,label:v==='__unset__'?'現場未設定':v,total:state.goods.filter(x=>(x.event||'__unset__')===v).reduce((sum,x)=>sum+Number(x.price||0)*Number(x.quantity||0),0)})); return `<section class="page-head"><div><h2>ホーム</h2><p>購入記録をひと目で確認</p></div></section>${venueChips()}<section class="stats"><div class="stat"><span>合計金額</span><strong>${yen(spent)}</strong></div><div class="stat"><span>購入個数</span><strong>${goods.reduce((a,x)=>a+Number(x.quantity||0),0)}個</strong></div><div class="stat"><span>手元の数</span><strong>${stock}個</strong></div></section><h3 class="section-title">現場名を追加</h3><form class="venue-form" id="venueForm"><input id="venueName" required placeholder="例：○○ライブ 東京公演" maxlength="80"><button class="button primary">追加</button></form><h3 class="section-title">現場ごとの合計金額</h3><section class="card">${venueTotals.length?venueTotals.map(x=>`<button class="venue-total" data-venue="${x.key==='__unset__'?'':esc(x.key)}"><span>${esc(x.label)}</span><strong>${yen(x.total)}</strong><i>›</i></button>`).join(''):empty('現場名を登録すると、ここに合計金額が表示されます')}</section><h3 class="section-title">最近登録したグッズ</h3><section class="card">${goods.length?goods.slice(-4).reverse().map(x=>row(x,'goods')).join(''):empty('この現場のグッズはまだありません')}</section><h3 class="section-title">購入予定</h3><section class="card">${filterVenue(state.plans).length?filterVenue(state.plans).slice(-3).reverse().map(x=>row(x,'plans')).join(''):empty('購入予定をメモしておけます')}</section>`; }
function listPage(type,title,subtitle){ const items=filterVenue(state[type]); const total=type==='goods'?items.reduce((sum,item)=>sum+Number(item.quantity||0)*Number(item.price||0),0):0; const planTotals=type==='plans'?[...new Set(state.plans.map(x=>x.event||'__unset__'))].map(event=>({event,label:event==='__unset__'?'現場未設定':event,total:state.plans.filter(x=>(x.event||'__unset__')===event).reduce((sum,x)=>sum+Number(x.price||0)*Number(x.quantity||1),0)})):[]; return `<section class="page-head"><div><h2>${title}</h2><p>${subtitle}</p></div></section>${venueChips()}${type==='goods'?`<div class="venue-summary"><strong>合計金額　${yen(total)}</strong><br>表示中のグッズの購入個数 × 金額を合計しています。</div>`:''}${type==='plans'?`<h3 class="section-title">現場ごとの購入予定合計</h3><section class="card">${planTotals.length?planTotals.map(x=>`<button class="venue-total" data-venue="${x.event==='__unset__'?'':esc(x.event)}"><span>${esc(x.label)}</span><strong>${yen(x.total)}</strong><i>›</i></button>`).join(''):empty('購入予定に金額を入れると、現場ごとの合計が表示されます')}</section>`:''}<input class="search" id="search" placeholder="グッズ名・現場名・メモで検索" /><section class="card" id="list">${items.length?items.slice().reverse().map(x=>row(x,type)).join(''):empty('まだ記録がありません')}</section><button class="floating" data-add="${type}">＋ ${title.replace('一覧','').replace('内訳','')}を登録</button>`; }
function render(){ app.innerHTML= page==='home'?home():page==='goods'?listPage('goods','グッズ一覧','買ったグッズと在庫を管理'):page==='random'?listPage('random','ランダム内訳','出たグッズを写真付きで記録'):listPage('plans','購入予定','購入数や合計には反映されません'); document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); }

function fields(type,item={}){ const options=venues().map(x=>`<option value="${esc(x)}">`).join(''); const common=`<label class="field">グッズ名<input name="name" required value="${esc(item.name||'')}" placeholder="例：アクリルスタンド"></label><label class="field">現場名<input name="event" list="venueOptions" value="${esc(item.event||'')}" placeholder="入力または候補から選択"><datalist id="venueOptions">${options}</datalist></label><label class="field">写真<input name="photo" type="file" accept="image/*"></label><label class="field">メモ<textarea name="memo" placeholder="サイズ・購入場所など">${esc(item.memo||'')}</textarea></label>`;
 if(type==='goods') return `${common}<label class="field">購入個数<input name="quantity" type="number" min="0" value="${item.quantity??1}"></label><label class="field">在庫数<input name="stock" type="number" min="0" value="${item.stock??0}"></label><label class="field">金額（1個あたり）<input name="price" type="number" min="0" value="${item.price??0}"></label>`;
 if(type==='random') return `${common}<label class="field">出た数<input name="quantity" type="number" min="1" value="${item.quantity??1}"></label>`;
 return `${common}<label class="field">予定個数<input name="quantity" type="number" min="1" value="${item.quantity??1}"></label><label class="field">予定金額（1個あたり）<input name="price" type="number" min="0" value="${item.price??0}" placeholder="例：2500"></label><label class="field">カテゴリ<select name="category"><option value="">選択しない</option>${['アクスタ','缶バッジ','紙もの','衣類','その他'].map(x=>`<option ${item.category===x?'selected':''}>${x}</option>`).join('')}</select></label>`;
}
function openForm(type,item){ editing={type,item}; document.querySelector('#dialogTitle').textContent=item?'編集する':`${type==='goods'?'グッズ':type==='random'?'開封結果':'購入予定'}を登録`; document.querySelector('#formFields').innerHTML=fields(type,item); document.querySelector('#entryDialog').showModal(); }
document.addEventListener('click', e=>{ const nav=e.target.closest('[data-page]'); if(nav){page=nav.dataset.page;render();} const add=e.target.closest('[data-add]'); if(add) openForm(add.dataset.add); const edit=e.target.closest('.edit'); if(edit) openForm(edit.dataset.type,state[edit.dataset.type].find(x=>x.id===edit.dataset.id)); const plus=e.target.closest('.plus'); if(plus){const x=state.random.find(x=>x.id===plus.dataset.id);x.quantity=Number(x.quantity||0)+1;save();} const del=e.target.closest('.delete'); if(del){pendingDelete={type:del.dataset.type,id:del.dataset.id};document.querySelector('#confirmText').textContent='この記録は端末から削除されます。';document.querySelector('#confirmDialog').showModal();} const chip=e.target.closest('[data-venue]'); if(chip){state.venue=chip.dataset.venue;save();} });
document.querySelector('#entryForm').addEventListener('submit', async e=>{ if(e.submitter?.value==='cancel')return; e.preventDefault(); const form=new FormData(e.currentTarget); const item=editing.item?{...editing.item}:{id:id(),photo:''}; for(const [k,v] of form.entries()) if(k!=='photo') item[k]=v; ['quantity','stock','price'].forEach(k=>{if(k in item)item[k]=Number(item[k]||0)}); const file=form.get('photo'); if(file?.size) item.photo=await compress(file); const list=state[editing.type]; const i=list.findIndex(x=>x.id===item.id); i<0?list.push(item):list[i]=item; document.querySelector('#entryDialog').close();save(); });
document.querySelector('#confirmDelete').addEventListener('click',()=>{if(!pendingDelete)return; state[pendingDelete.type]=state[pendingDelete.type].filter(x=>x.id!==pendingDelete.id); if(pendingDelete.type==='goods')state.random=state.random.filter(x=>x.goodsId!==pendingDelete.id);save();pendingDelete=null;});
document.addEventListener('submit',e=>{if(e.target.id!=='venueForm')return;e.preventDefault();const name=e.target.querySelector('#venueName').value.trim();if(!name)return;if(!state.venueNames.includes(name))state.venueNames.push(name);e.target.reset();save();});
document.addEventListener('input',e=>{if(e.target.id!=='search')return; const q=e.target.value.toLowerCase();const type=page;document.querySelector('#list').innerHTML=filterVenue(state[type]).filter(x=>[x.name,x.event,x.memo].join(' ').toLowerCase().includes(q)).slice().reverse().map(x=>row(x,type)).join('')||empty('該当する記録はありません');});
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const max=900,s=Math.min(1,max/Math.max(im.width,im.height));const c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.78));};im.src=r.result;};r.onerror=reject;r.readAsDataURL(file);});}
document.querySelector('#exportButton').addEventListener('click',()=>{const choice=confirm('OK：データを書き出す\nキャンセル：バックアップを読み込む');if(choice){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`goods-log-${new Date().toISOString().slice(0,10)}.json`;a.click();}else document.querySelector('#importInput').click();});
document.querySelector('#importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{state={...initial,...JSON.parse(await file.text())};save();alert('バックアップを読み込みました。')}catch{alert('読み込めませんでした。JSON形式のバックアップを選んでください。')}});
if('serviceWorker'in navigator) navigator.serviceWorker.register('./sw.js'); render();

